### ISSUE TITLE
Program doesn't run in conda

### ISSUE THREAD

**Issue by desmodus1984** [bardetlab/methylasso#4]
Hi,

I installed the program using the conda instructions and when I tried running the code, after activating the environment it doesn't work.

`nohup Rscript /home/juaguila/appz/methylasso-main/MethyLasso.R --n1 HIGH --c1 V00001.deduplicated.bismark.cov.gz,V00750.deduplicated.bismark.cov.gz,V00796.deduplicated.bismark.cov.gz --n2 LOW --c2 V00294.deduplicated.bismark.cov.gz,V00296.deduplicated.bismark.cov.gz,V00297.deduplicated.bismark.cov.gz -c 10 --meth 5 -q 0.05 -o test-low-high -t 10`

I got the error "Fatal error: cannot open file 'MethyLasso.R': No such file or directory".
Then I tried coping the file, and I got this error: 
"Error in library(R.utils) : there is no package called ‘R.utils’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted"

**Comment by delbala** [comment]
Hi, 

I modified the conda conda_env.yml script to install the R.Utils package. It should work now.

Additionally, there is an error in your code. If you add the `--meth` option, you must also include the `--cov` option, as indicated in the README in Section 4 - Input Format. 

If you don't specify an input format, it will by default take the bismark input format: `chr / start / end / percent_methylation / count_methylated / count_unmethylated`.
Alternatively, if you provide an input format different from bismark, you must specify the column numbers where the methylated AND unmethylated C's are located (`--mC` and `--uC` ) 
OR  you only specify the coverage AND methylation percentage columns (`--cov` and `--meth`)

I hope I was able to help you.
Delphine

**Comment by desmodus1984** [comment]
Good morning Delphine,

Should I reinstall methylasso or can I just update it in conda?

Thank you very much.

Juan Pablo Aguilar
________________________________
From: Delphine Balaramane ***@***.***>
Sent: Thursday, March 28, 2024 9:14:21 AM
To: abardet/methylasso ***@***.***>
Cc: Aguilar Cabezas, Juan Pablo ***@***.***>; Author ***@***.***>
Subject: [External] Re: [abardet/methylasso] Program doesn't run in conda (Issue #4)

Use caution with links and attachments.

Hi,

I modified the conda conda_env.yml script to install the R.Utils package. It should work now.

Additionally, there is an error in your code. If you add the --meth option, you must also include the --cov option, as indicated in the README in Section 4 - Input Format.

If you don't specify an input format, it will by default take the bismark input format: chr / start / end / percent_methylation / count_methylated / count_unmethylated.
Alternatively, if you provide an input format different from bismark, you must specify the column numbers where the methylated AND unmethylated C's are located (--mC and --uC )
OR you only specify the coverage AND methylation percentage columns (--cov and --meth)

I hope I was able to help you.
Delphine

**Comment by delbala** [comment]
Hi, 

You need to re-download the methylasso package from github to get the new version and install it again. 

Best, 
Delphine

**Comment by desmodus1984** [comment]
Hi,
I created another environment and installed all the required packages and methylasso.
I tried running it two times and it failed.

The first attempt, I used the bismark files, with the following code

nohup Rscript /home/juaguila/appz/methylasso-main/MethyLasso.R --n1 HIGH --c1 V00001.deduplicated.bismark.cov.gz,V00750.deduplicated.bismark.cov.gz,V00796.deduplicated.bismark.cov.gz --n2 LOW --c2 V00294.deduplicated.bismark.cov.gz,V00296.deduplicated.bismark.cov.gz, V00297_methyldackel_CpG.bedGraph -c 10 -q 0.05 -o test-low-high -t 20 > methylasso1.log

It ran well for a while and then failed.



*      *   * * * *   * * * *   *     *   *     *   *            *      * * * *   * * * *   * * * *
* *  * *   *            *      *     *    *   *    *           * *     *         *         *     *
*  **  *   * * *        *      * * * *     * *     *          *   *    * * * *   * * * *   *     *
*      *   *            *      *     *      *      *         * * * *         *         *   *     *
*      *   * * * *      *      *     *     *       * * * *  *       *  * * * *   * * * *   * * * *

Reading condition HIGH with 3 replicate(s) in memory..
Reading condition LOW with 3 replicate(s) in memory..

Part 1: Beginning analysis of the levels of DNA methylation in a single condition

Step 1: Fit of methylation signal

Processing chromosome: NW_022882922.1 
Processing chromosome: NW_022882923.1 
Processing chromosome: NW_022882924.1 
Processing chromosome: NW_022882925.1 
Processing chromosome: NW_022882926.1 
Processing chromosome: NW_022882927.1 
Processing chromosome: NW_022882928.1 
Processing chromosome: NW_022882929.1 
Processing chromosome: NW_022882930.1 
Processing chromosome: NW_022882931.1 
Processing chromosome: NW_022882949.1 
Processing chromosome: NW_022882932.1 
Processing chromosome: NW_022882933.1 
Processing chromosome: NW_022882935.1 
Processing chromosome: NW_022882934.1 
Processing chromosome: NW_022882953.1 
Processing chromosome: NW_022882948.1 
Processing chromosome: NW_022882936.1 
Processing chromosome: NW_022882952.1 
Processing chromosome: NW_022882974.1 
Processing chromosome: NW_022882954.1 
Processing chromosome: NW_022882957.1 
Processing chromosome: NW_022882937.1 
Processing chromosome: NW_022882942.1 
Processing chromosome: NW_022882971.1 
Processing chromosome: NW_022882994.1 
Processing chromosome: NW_022882991.1 
Processing chromosome: NW_022882938.1 
Processing chromosome: NW_022882955.1 
Processing chromosome: NW_022883013.1 
Processing chromosome: NW_022883033.1 
Processing chromosome: NW_022882958.1 
Processing chromosome: NW_022883053.1 
Processing chromosome: NW_022882939.1 
Processing chromosome: NW_022883073.1 
Processing chromosome: NW_022882978.1 
Processing chromosome: NW_022883096.1 
Processing chromosome: NW_022882977.1 
Processing chromosome: NW_022882970.1 
Processing chromosome: NW_022882998.1 
Processing chromosome: NW_022883116.1 
Processing chromosome: NW_022882990.1 
Processing chromosome: NW_022883136.1 
Processing chromosome: NW_022883156.1 
Processing chromosome: NW_022883176.1 
Processing chromosome: NW_022883020.1 
Processing chromosome: NW_022882940.1 
Processing chromosome: NW_022883197.1 
Processing chromosome: NW_022883217.1 
Processing chromosome: NW_022883238.1 
Processing chromosome: NW_022883258.1 
Processing chromosome: NW_022883278.1 
Processing chromosome: NW_022883016.1 
Processing chromosome: NW_022882941.1 
Processing chromosome: NW_022883298.1 
Processing chromosome: NW_022883036.1 
Processing chromosome: NW_022883319.1 
Processing chromosome: NW_022882961.1 
Processing chromosome: NW_022883339.1 
Processing chromosome: NW_022883361.1 
Processing chromosome: NW_022883381.1 
Processing chromosome: NW_022883040.1 
Processing chromosome: NW_022883060.1 
Processing chromosome: NW_022883402.1 
Processing chromosome: NW_022883080.1 
Processing chromosome: NW_022882951.1 
Processing chromosome: NW_022883423.1 
Processing chromosome: NW_022883103.1 
Processing chromosome: NW_022883443.1 
Processing chromosome: NW_022883123.1 
Processing chromosome: NW_022883464.1 
Processing chromosome: NW_022883143.1 
Processing chromosome: NW_022883012.1 
Processing chromosome: NW_022882960.1 
Processing chromosome: NW_022883163.1 
Processing chromosome: NW_022883056.1 
Processing chromosome: NW_022882962.1 
Processing chromosome: NW_022883484.1 
Processing chromosome: NW_022883184.1 
Processing chromosome: NW_022883504.1 
Processing chromosome: NW_022883204.1 
Processing chromosome: NW_022882946.1 
Processing chromosome: NW_022883524.1 
Processing chromosome: NW_022883224.1 
Processing chromosome: NW_022883546.1 
Processing chromosome: NW_022883245.1 
Processing chromosome:Processing chromosome:  NW_022883568.1NW_022883265.1  

Processing chromosome: NW_022883589.1 
Processing chromosome: NW_022883285.1 
Processing chromosome: NW_022883609.1 
Processing chromosome: NW_022883305.1 
Processing chromosome: NW_022882982.1 
Processing chromosome: NW_022883076.1 
Processing chromosome: NW_022883629.1 
Processing chromosome: NW_022883032.1 
Processing chromosome: NW_022883002.1 
Processing chromosome: NW_022883099.1 
Processing chromosome: NW_022883649.1 
Processing chromosome: Processing chromosome:NW_022883024.1  NW_022883670.1
 
and I got the following error:

Processing chromosome: NW_022884269.1 
Processing chromosome: NW_022884289.1 
Processing chromosome: NW_022884311.1 
Processing chromosome: NW_022884332.1 
Processing chromosome: NW_022883091.1 
Processing chromosome: NW_022883919.1 
Processing chromosome: NW_022884350.1 
Processing chromosome: NW_022883890.1 
Processing chromosome: NW_022884298.1 

Warning: the following chromosomes did not work: NW_022882943.1 NW_022882952.1 NW_022882973.1 NW_022883011.1 NW_022883040.1 NW_022883065.1 NW_022883072.1 NW_022883073.1 NW_022883097.1 NW_022883171.1 NW_022883173.1 NW_022883199.1 NW_022883203.1 NW_022883215.1 NW_022883240.1 NW_022883247.1 NW_022883249.1 NW_022883311.1 NW_022883323.1 NW_022883358.1 NW_022883373.1 NW_022883401.1 NW_022883404.1 NW_022883444.1 NW_022883450.1 NW_022883458.1 NW_022883465.1 NW_022883496.1 NW_022883513.1 NW_022883515.1 NW_022883537.1 NW_022883540.1 NW_022883552.1 NW_022883579.1 NW_022883592.1 NW_022883615.1 NW_022883616.1 NW_022883642.1 NW_022883667.1 NW_022883676.1 NW_022883688.1 NW_022883743.1 NW_022883758.1 NW_022883770.1 NW_022883775.1 NW_022883780.1 NW_022883782.1 NW_022883796.1 NW_022883815.1 NW_022883844.1 NW_022883846.1 NW_022883855.1 NW_022883859.1 NW_022883896.1 NW_022883953.1 NW_022883959.1 NW_022883969.1 NW_022883975.1 NW_022884003.1 NW_022884028.1 NW_022884062.1 NW_022884068.1 NW_022884071.1 NW_022884082.1 NW_022884096.1 NW_022884106.1 NW_022884110.1 NW_022884116.1 NW_022884119.1 NW_022884131.1 NW_022884176.1 NW_022884181.1 NW_022884196.1 NW_022884203.1 NW_022884216.1 NW_022884222.1 NW_022884327.1 NW_022884349.1 NW_022882956.1 NW_022883091.1 NW_022883179.1 NW_022883236.1 NW_022883315.1 NW_022883357.1 NW_022883391.1 NW_022883449.1 NW_022883528.1 NW_022883543.1 NW_022883561.1 NW_022883562.1 NW_022883581.1 NW_022883656.1 NW_022883690.1 NW_022883694.1 NW_022883726.1 NW_022883749.1 NW_022883865.1 NW_022883890.1 NW_022883895.1 NW_022883919.1 NW_022883944.1 NW_022883973.1 NW_022883978.1 NW_022884002.1 NW_022884066.1 NW_022884114.1 NW_022884155.1 NW_022884169.1 NW_022884177.1 NW_022884213.1 NW_022884214.1 NW_022884302.1 NW_022884329.1 NW_022883954.1 NW_022884144.1 NW_022882967.1 NW_022883090.1 NW_022884298.1 NW_022883791.1
Step 2: Segmentation and identification of PMDs, LMRs, UMRs and DMVs


 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .External(list(name = "InternalFunction_invoke", address = <pointer: 0x55c2be4960c0>,     dll = list(name = "Rcpp", path = "/home/juaguila/.conda/envs/methylasso/lib/R/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x55c2c1116b50>,         info = <pointer: 0x55c2b986dca0>), numParameters = -1L),     <pointer: 0x55c2b936d4c0>, data, tol_val)
 2: MethyLasso:::segment_methylation_helper(sig.df, tol_val = tol_val)
 3: as.data.table(MethyLasso:::segment_methylation_helper(sig.df,     tol_val = tol_val))
 4: MethyLasso:::segment_methylation_singlechr(mdata, mret, ...)
 5: eval(c.expr, envir = args, enclos = envir)
 6: eval(c.expr, envir = args, enclos = envir)
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(eval(c.expr, envir = args, enclos = envir), error = function(e) e)
11: FUN(X[[i]], ...)
12: lapply(X = S, FUN = FUN, ...)
13: doTryCatch(return(expr), name, parentenv, handler)
14: tryCatchOne(expr, names, parentenv, handlers[[1L]])
15: tryCatchList(expr, classes, parentenv, handlers)
16: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call, nlines = 1L)        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
17: try(lapply(X = S, FUN = FUN, ...), silent = TRUE)
18: sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE))
19: FUN(X[[i]], ...)
20: lapply(seq_len(cores), inner.do)
21: mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,     mc.silent = silent, mc.cores = cores)
22: e$fun(obj, substitute(ex), parent.frame(), e$data)
23: foreach(ch = data[, unique(chr)], .combine = function(x, y) {    list(lmr_umr_valley = rbind(x$lmr_umr_valley, y$lmr_umr_valley),         pmd = rbind(x$pmd, y$pmd), ov = rbind(x$ov, y$ov))}) %dopar% {    mdata = data[chr == ch]    mret = list(estimates = ret$estimates[ret$estimates$chr ==         ch, ], detection.type = ret$detection.type, ref.cond = ret$ref.cond)    segments = MethyLasso:::segment_methylation_singlechr(mdata,         mret, ...)    segments$lmr_umr_valley[, `:=`(chr, ch)]    segments$pmd[, `:=`(chr, ch)]    segments$ov[, `:=`(chr, ch)]    segments}
24: MethyLasso:::segment_methylation(data, ret, ncores = t, pmd_max_beta = m,     min_num_cpgs = n)
An irrecoverable exception occurred. R is aborting now ...

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .External(list(name = "InternalFunction_invoke", address = <pointer: 0x55c2be4960c0>,     dll = list(name = "Rcpp", path = "/home/juaguila/.conda/envs/methylasso/lib/R/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x55c2c1116b50>,         info = <pointer: 0x55c2b986dca0>), numParameters = -1L),     <pointer: 0x55c2b936d4c0>, data, tol_val)
 2: MethyLasso:::segment_methylation_helper(sig.df, tol_val = tol_val)
 3: as.data.table(MethyLasso:::segment_methylation_helper(sig.df,     tol_val = tol_val))
 4: MethyLasso:::segment_methylation_singlechr(mdata, mret, ...)
 5: eval(c.expr, envir = args, enclos = envir)
 6: eval(c.expr, envir = args, enclos = envir)
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(eval(c.expr, envir = args, enclos = envir), error = function(e) e)
11: FUN(X[[i]], ...)
12: lapply(X = S, FUN = FUN, ...)
13: doTryCatch(return(expr), name, parentenv, handler)
14: tryCatchOne(expr, names, parentenv, handlers[[1L]])
15: tryCatchList(expr, classes, parentenv, handlers)
16: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call, nlines = 1L)        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
17: try(lapply(X = S, FUN = FUN, ...), silent = TRUE)
18: sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE))
19: FUN(X[[i]], ...)
20: lapply(seq_len(cores), inner.do)
21: mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,     mc.silent = silent, mc.cores = cores)
22: e$fun(obj, substitute(ex), parent.frame(), e$data)
23: foreach(ch = data[, unique(chr)], .combine = function(x, y) {    list(lmr_umr_valley = rbind(x$lmr_umr_valley, y$lmr_umr_valley),         pmd = rbind(x$pmd, y$pmd), ov = rbind(x$ov, y$ov))}) %dopar% {    mdata = data[chr == ch]    mret = list(estimates = ret$estimates[ret$estimates$chr ==         ch, ], detection.type = ret$detection.type, ref.cond = ret$ref.cond)    segments = MethyLasso:::segment_methylation_singlechr(mdata,         mret, ...)    segments$lmr_umr_valley[, `:=`(chr, ch)]    segments$pmd[, `:=`(chr, ch)]    segments$ov[, `:=`(chr, ch)]    segments}
24: MethyLasso:::segment_methylation(data, ret, ncores = t, pmd_max_beta = m,     min_num_cpgs = n)
An irrecoverable exception occurred. R is aborting now ...

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .External(list(name = "InternalFunction_invoke", address = <pointer: 0x55c2be4960c0>,     dll = list(name = "Rcpp", path = "/home/juaguila/.conda/envs/methylasso/lib/R/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x55c2c1116b50>,         info = <pointer: 0x55c2b986dca0>), numParameters = -1L),     <pointer: 0x55c2b936d4c0>, data, tol_val)
 2: MethyLasso:::segment_methylation_helper(sig.df, tol_val = tol_val)
 3: as.data.table(MethyLasso:::segment_methylation_helper(sig.df,     tol_val = tol_val))
 4: MethyLasso:::segment_methylation_singlechr(mdata, mret, ...)
 5: eval(c.expr, envir = args, enclos = envir)
 6: eval(c.expr, envir = args, enclos = envir)
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(eval(c.expr, envir = args, enclos = envir), error = function(e) e)
11: FUN(X[[i]], ...)
12: lapply(X = S, FUN = FUN, ...)
13: doTryCatch(return(expr), name, parentenv, handler)
14: tryCatchOne(expr, names, parentenv, handlers[[1L]])
15: tryCatchList(expr, classes, parentenv, handlers)
16: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call, nlines = 1L)        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
17: try(lapply(X = S, FUN = FUN, ...), silent = TRUE)
18: sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE))
19: FUN(X[[i]], ...)
20: lapply(seq_len(cores), inner.do)
21: mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,     mc.silent = silent, mc.cores = cores)
22: e$fun(obj, substitute(ex), parent.frame(), e$data)
23: foreach(ch = data[, unique(chr)], .combine = function(x, y) {    list(lmr_umr_valley = rbind(x$lmr_umr_valley, y$lmr_umr_valley),         pmd = rbind(x$pmd, y$pmd), ov = rbind(x$ov, y$ov))}) %dopar% {    mdata = data[chr == ch]    mret = list(estimates = ret$estimates[ret$estimates$chr ==         ch, ], detection.type = ret$detection.type, ref.cond = ret$ref.cond)    segments = MethyLasso:::segment_methylation_singlechr(mdata,         mret, ...)    segments$lmr_umr_valley[, `:=`(chr, ch)]    segments$pmd[, `:=`(chr, ch)]    segments$ov[, `:=`(chr, ch)]    segments}
24: MethyLasso:::segment_methylation(data, ret, ncores = t, pmd_max_beta = m,     min_num_cpgs = n)
An irrecoverable exception occurred. R is aborting now ...

 *** caught segfault ***
address (nil), cause 'memory not mapped'


Then, I tried running the bedgraph files generated with methyldackel, which have the same input format, though I had to eliminate the first line which is weird:

and I used the following code to eliminate the first line
for i in *_methyldackel_CpG.bedGraph
        do
	base=$(basename $i "_R1_val_1.fq.gz")
        tail -n +2 ${base}_methyldackel_CpG.bedGraph > ${base}_CpG.bedGraph

done

and then, this to run methylasso
nohup Rscript /home/juaguila/appz/methylasso-main/MethyLasso.R --n1 HIGH --c1 V00001_methyldackel_CpG.bedGraph_CpG.bedGraph,V00750_methyldackel_CpG.bedGraph_CpG.bedGraph,V00796_methyldackel_CpG.bedGraph_CpG.bedGraph --n2 LOW --c2 V00294_methyldackel_CpG.bedGraph_CpG.bedGraph,V00296_methyldackel_CpG.bedGraph_CpG.bedGraph, V00297_methyldackel_CpG.bedGraph_CpG.bedGraph -c 10 -q 0.05 -o test-low-high -t 20 > methylasso1.log


and I got the following error:


*      *   * * * *   * * * *   *     *   *     *   *            *      * * * *   * * * *   * * * *
* *  * *   *            *      *     *    *   *    *           * *     *         *         *     *
*  **  *   * * *        *      * * * *     * *     *          *   *    * * * *   * * * *   *     *
*      *   *            *      *     *      *	   *         * * * *         *         *   *     *
*      *   * * * *	*      *     *     *	   * * * *  *       *  * * * *   * * * *   * * * *

Reading condition HIGH with 3 replicate(s) in memory..
Reading condition LOW with 3 replicate(s) in memory..
Error in fread(file_path) :
  Input is empty or only contains BOM or terminal control characters
Calls: lapply -> FUN -> lapply -> FUN -> process_replicate -> fread
Execution halted


The methyldackel files, should be fine. From the bismark files I got even the graphs, but I was shocked that according to methylKit, the depth is supposed to be ~ 30X; the graphs showed it to be less than 1X.
I understand that bismark has a deduplication step, but that level of reduction was shocking.

I checked the methyldackel files, with used a bam files that had read deduplication by Picard, but MethylKit showed medium-high depth, and they look okay
(methylasso) [juaguila@u05 Rec-5]$ head V00001_methyldackel_CpG.bedGraph_CpG.bedGraph
NW_022882922.1	3064	3065	0	0	1
NW_022882922.1	3071	3072	0	0	1
NW_022882922.1	3804	3805	0	0	1
NW_022882922.1	3829	3830	0	0	1
NW_022882922.1	3839	3840	0	0	1
NW_022882922.1	3845	3846	0	0	1
NW_022882922.1	3847	3848	0	0	1
NW_022882922.1	3869	3870	0	0	1
NW_022882922.1	3912	3913	0	0	1
NW_022882922.1	4855	4856	0	0	2

(methylasso) [juaguila@u05 Rec-5]$ head V00297_methyldackel_CpG.bedGraph_CpG.bedGraph
NW_022882922.1	4855	4856	0	0	5
NW_022882922.1	4865	4866	0	0	5
NW_022882922.1	4888	4889	0	0	6
NW_022882922.1	4891	4892	0	0	6
NW_022882922.1	4903	4904	0	0	7
NW_022882922.1	4952	4953	0	0	7
NW_022882922.1	4961	4962	0	0	6
NW_022882922.1	4965	4966	0	0	7
NW_022882922.1	4975	4976	0	0	7
NW_022882922.1	5048	5049	0	0	10

Any suggestion about what might be causing that error with the methyldackel files?

Thank you very much.
I ran the analysis in a server with 48 cores and 500G of Ram.

**Comment by delbala** [comment]
Hi, 

You have a typo on your both code, you have an extra space after the comma in the option `--C2`

To be able to answer you, I need to see what your input files look like. Can you give me a head of the file V00001.deduplicated.bismark.cov.gz and can you also tell me what the columns in file V00001_methyldackel_CpG.bedGraph_CpG.bedGraph  correspond to ?

Best, 
Delphine

**Comment by desmodus1984** [comment]
Hi Delphine

The head of V00001.deduplicated.bismark.cov.gz is

 gzip -cd V00001.deduplicated.bismark.cov.gz | head
NW_022882922.1  3066    3066    0       0       1
NW_022882922.1  3073    3073    0       0       1
NW_022882922.1  3131    3131    0       0       1
NW_022882922.1  3138    3138    0       0       1
NW_022882922.1  3158    3158    0       0       1
NW_022882922.1  3177    3177    0       0       1
NW_022882922.1  3405    3405    0       0       1
NW_022882922.1  3423    3423    0       0       1
NW_022882922.1  3453    3453    0       0       1
NW_022882922.1  3465    3465    0       0       1



The columns of V00001_methyldackel_CpG.bedGraph_CpG.bedGraph  are

The chromosome/contig/scaffold name

The start coordinate

The end coordinate

The methylation percentage rounded to an integer

The number of alignments/pairs reporting methylated bases

The number of alignments/pairs reporting unmethylated bases


Let me know if you need further information.



Juan Pablo Aguilar Cabezas

________________________________
From: Delphine Balaramane ***@***.***>
Sent: Friday, April 5, 2024 7:53 AM
To: abardet/methylasso ***@***.***>
Cc: Aguilar Cabezas, Juan Pablo ***@***.***>; Author ***@***.***>
Subject: [External] Re: [abardet/methylasso] Program doesn't run in conda (Issue #4)

Use caution with links and attachments.

Hi,

You have a typo on your both code, you have an extra space after the comma in the option --C2

To be able to answer you, I need to see what your input files look like. Can you give me a head of the file V00001.deduplicated.bismark.cov.gz and can you also tell me what the columns in file V00001_methyldackel_CpG.bedGraph_CpG.bedGraph correspond to ?

Best,
Delphine

**Comment by delbala** [comment]
Hi, 

Unfortunately, I haven't been able to find a solution to your problem. I reviewed the input files, and they don't seem to have any apparent issues.

However, please ensure that the columns in your input files are properly separated by tabs, as incorrect delimiters can sometimes cause these errors. I would also suggest trying to rerun the code after addressing the typos mentioned earlier.

Delphine

**Comment by abardet** [comment]
Dear desmodus1984,
While looking for a solution for issue #11, I found out that this error might be due to chromosomes that are unconventional and short. Since your data also looks like it has unconventional chromosomes, this could be the issue. You could try restricting to chromosomes that are relatively big in size. Let me know if this solved your issue.
Best,
Anaïs
