### ISSUE TITLE
Why round p-value and FDR to 4 digits in DMR output?

### ISSUE THREAD

**Issue by benbfly** [bardetlab/methylasso#9]
Is there some reason we shouldn't use p and FDR values <1E-4 ?   It would be useful to see smaller values.

See code:
https://github.com/bardetlab/methylasso/blob/b61fe626300705e35f1bf21fcc27fe7d31715758/MethyLasso.R#L413

**Comment by abardet** [comment]
Dear Ben, no reason at all indeed. I just removed the round. Happy to get your feedback on MethyLasso once you have used it ;-) Best, Anaïs

**Comment by abardet** [comment]
Dear Ben,
For your information, if you were using bismark output files as input to MethyLasso, we just fixed an issue in MethyLasso.R to take the correct columns as input so this file should be replaced or options "--mC 5 --uC 6" specified.
I'm very sorry for that.
Best,
Anaïs
